#!/bin/sh
# Main ToxBank-investigation install script
# Author: Christoph Helma, Andreas Maunz, Denis Gebele.

if [ "$(id -u)" = "0" ]; then
  echo "This script must not be run as root" 1>&2
  exit 1
fi

LOG="/tmp/`basename $0`-log.txt"
. "./utils.sh"
echo
echo "ToxBank-investigation installation."
echo "You may need to give root password for some privileged actions right now and later:"
echo
cmd="sudo echo -n \"\"" && run_cmd "$cmd" "Acquire privileges"

echo "Cleaning up /tmp files."
sudo rm -rf /tmp/ruby* /tmp/passenger* 

. "./base-install.sh"
. "./ruby.sh"

if [ "$install" != "gem" ]
then
  . "./nginx.sh"
  . "./investigation-services.sh"
fi

cd $TB_HOME
mkdir -p investigation
mkdir -p java
mkdir -p public
mkdir -p tmp

cd java
wget https://github.com/downloads/ISA-tools/ISAvalidator-ISAconverter-BIImanager/ISA-validator-1.4.zip
unzip ISA-validator-1.4.zip
wget https://github.com/downloads/ToxBank/isa2rdf/isa2rdf-0.0.1-SNAPSHOT.jar
cd -

# get, compile, install "raptor" "rasqal"
# raptor
cd tmp
wget http://download.librdf.org/source/raptor2-2.0.4.tar.gz
tar xvzf raptor2-2.0.4.tar.gz
cd raptor2-2.0.4 >>$LOG 2>&1
./configure
make
sudo make install
cd -

# rasqal
wget http://download.librdf.org/source/rasqal-0.9.27.tar.gz
tar xvzf rasqal-0.9.27.tar.gz
cd rasqal-0.9.27
./configure >>$LOG 2>&1
make
sudo make install
cd -

# 4store
wget http://4store.org/download/4store-v1.1.4.tar.gz
tar xvzf 4store-v1.1.4.tar.gz
cd 4store-v1.1.4
./configure --with-storage-path=$TB_PREFIX/4store >>$LOG 2>&1
make >>$LOG 2>&1
sudo make install
sudo /sbin/ldconfig
cd $TB_HOME
sudo rm -r tmp

# start 4s service
4s-backend-setup ToxBank
4s-backend ToxBank

cd investigation
git init
echo "*/*.zip" > .gitignore
echo "*/tmp" >> .gitignore
git add .gitignore
git commit -am ".gitignore added"
cd -

servername="`hostname`"
serverdomain="`dnsdomainname`"
if [ -n "$serverdomain" ]; then
  servername="$servername"."$serverdomain"
fi
escapedserver="`echo $servername | sed 's/\/\\\//'`"

if [ "$TB_BRANCH" = "development" ]; then
  logger=":logger: backtrace"
else
  logger=""
fi

if [ "$TB_INSTALL" = "server" ]; then
  aa="https:\/\/opensso.in-silico.ch"
else
  aa=""
fi

mkdir -p "$HOME/.toxbank/config" >>$LOG 2>&1
mkdir -p "$HOME/.toxbank/log" >>$LOG 2>&1
mkdir -p "$HOME/.toxbank/tmp" >>$LOG 2>&1

$GIT checkout production.yaml      >>$LOG 2>&1
$GIT checkout aa-$TB_INSTALL.yaml  >>$LOG 2>&1

cmd="sed -e \"s,SERVERNAME,$servername,;s,ESCAPEDSERVER,$escapedserver,;s,LOGGER,$logger,;s,AA,$aa,;s,WWW_DEST,$WWW_DEST,;s,NGINX_PORT,$NGINX_PORT,;s,OHM_PORT,$OHM_PORT,\" production.yaml > $HOME/.toxbank/config/production.yaml" && run_cmd "$cmd" "Config 1"
cmd="sed -e \"s,SERVERNAME,$servername,;s,ESCAPEDSERVER,$escapedserver,;s,LOGGER,$logger,;s,AA,$aa,;s,WWW_DEST,$WWW_DEST,;s,NGINX_PORT,$NGINX_PORT,;s,OHM_PORT,$OHM_PORT,\" aa-$TB_INSTALL.yaml >> $HOME/.toxbank/config/production.yaml" && run_cmd "$cmd" "Config 2"

echo
echo "Installation finished and system configured."
echo "Destination: '$TB_PREFIX'"
echo "Nginx: '$NGINX_DEST'"
echo "IMPORTANT: Include the file '$TB_UI_CONF' in your shell or system startup to have the system automatically configured."
echo
